ITEMS=[
('Polity','Constitution & Governance','The Supreme Court reiterates the importance of timely assent to Bills','A constitutional democracy depends on clear processes between elected legislatures and constitutional offices. Debate around assent to Bills renews attention to timelines and remedies under the Constitution.','The question touches the balance between constitutional offices and elected governments. Predictable timelines help prevent a legislative vacuum while preserving constitutional review.','GS-II'),
('Economy','Banking & Finance','RBI keeps the focus on inflation while supporting stable growth','Monetary policy decisions weigh price stability against growth. Food prices and global uncertainty remain important inputs for the policy outlook.','Inflation affects household purchasing power, savings and the cost of borrowing. The policy trade-off is a recurring issue in macroeconomic management.','GS-III'),
('Environment','Climate & Ecology','Restoration of urban wetlands gains attention in climate planning','Wetlands absorb excess rainwater, support biodiversity and store carbon. Cities explore nature-based solutions alongside built infrastructure.','Healthy wetlands can reduce flood risk and provide ecological services, but restoration needs land-use protection and community participation.','GS-III'),
('International Relations','Global Institutions','Reform of multilateral institutions remains on the global agenda','Calls for more representative global institutions reflect changes in economic and political power. Reform debates include representation, financing and decision-making.','India’s engagement with multilateral reform links its development priorities with the future of global governance.','GS-II'),
('Science & Technology','Digital Public Infrastructure','Digital public infrastructure raises questions of access and safeguards','Digital identity and payment systems can make public services easier to deliver. Their design must also account for privacy, accessibility and resilience.','The policy challenge is to combine innovation with rights-based safeguards and inclusion for people with limited connectivity.','GS-III'),
('Geography','Water Resources','River basin planning offers a wider view of water management','Water systems cross administrative boundaries. Basin-level planning can connect irrigation, drinking water, floods and ecosystem needs.','Integrated planning can reduce competing demands, but requires reliable data and cooperation among states and local institutions.','GS-I'),
('Society','Health & Education','Community health workers strengthen last-mile public health','Frontline workers connect households with health information, screening and public services, particularly in underserved areas.','Their role highlights how public health outcomes depend on trust, local knowledge and well-supported primary care.','GS-II'),
('Governance','Public Policy','Social audits can improve accountability in welfare delivery','Social audits enable beneficiaries and communities to examine whether public programmes reach intended recipients and meet standards.','Public participation can surface implementation gaps and build trust when findings lead to timely corrective action.','GS-II'),
('Security','Cybersecurity','Critical infrastructure protection needs a whole-of-system approach','Power, transport and communications rely on connected digital systems. Preparedness includes prevention, incident response and recovery.','Cyber resilience requires coordination between government, operators and technology providers, as well as trained personnel and clear protocols.','GS-III'),
('Economy','Agriculture','Millets feature in conversations on nutrition and climate resilience','Millets are suited to diverse agro-climatic conditions and can contribute to dietary diversity. Market access and consumer demand shape farmer incentives.','Crop diversification can support resilience, but requires procurement, processing and awareness to create sustained demand.','GS-III'),
('Environment','Renewable Energy','Grid flexibility becomes essential as renewable capacity expands','Variable renewable generation increases the value of storage, flexible demand and stronger transmission networks.','A reliable clean-energy transition depends on matching generation with demand while maintaining grid stability and affordability.','GS-III'),
('Polity','Federalism','Inter-state councils provide a forum for cooperative federalism','Coordination among states and the Union is important for policies that cross jurisdictional lines, from public health to transport.','Institutional dialogue can resolve differences early and improve policy design for a diverse federation.','GS-II')]
ITEMS=[ITEMS[i%len(ITEMS)] for i in range(36)]
